# Generated by Django 3.2.5 on 2021-08-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('primary_logo', models.ImageField(upload_to='basic')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='basic')),
                ('main_cover_image', models.ImageField(blank='True', null=True, upload_to='basic')),
                ('official_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('help_line', models.CharField(blank=True, max_length=20, null=True)),
                ('physical_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.siteinfo')),
            ],
        ),
    ]
