# Generated by Django 3.2.5 on 2021-08-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sponsor_details',
            name='site',
        ),
        migrations.RemoveField(
            model_name='top_achivment',
            name='site',
        ),
        migrations.DeleteModel(
            name='SiteAbout',
        ),
        migrations.DeleteModel(
            name='SocialMediaLinks',
        ),
        migrations.DeleteModel(
            name='sponsor_details',
        ),
        migrations.DeleteModel(
            name='Top_achivment',
        ),
    ]
