# Generated by Django 3.2.5 on 2021-08-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
