# Generated by Django 3.2.5 on 2021-08-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_siteabout_socialmedialinks_sponsor_details_top_achivment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_achivment',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.siteinfo'),
        ),
    ]
