# Generated by Django 3.2.5 on 2021-08-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_top_achivment_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor_details',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.siteinfo'),
        ),
    ]
