# Generated by Django 3.2.5 on 2021-08-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_sponsor_details_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteabout',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='basic'),
        ),
    ]
