# Generated by Django 3.2.5 on 2021-08-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_siteabout_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteabout',
            name='banner',
            field=models.ImageField(blank=True, default='../static/images/common/esport-team-landing-news-big.jpg', null=True, upload_to='basic'),
        ),
    ]
