# Generated by Django 3.2.5 on 2021-08-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_legendzone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legendzone',
            name='title',
        ),
        migrations.AddField(
            model_name='legendzone',
            name='Caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
