# Generated by Django 3.2.5 on 2021-08-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20210812_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_admin_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
