# Generated by Django 3.2.5 on 2021-08-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharemediaortext',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersocialmedia',
            name='user',
        ),
    ]
