# Generated by Django 4.1 on 2022-09-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.BooleanField(default=False),
        ),
    ]
