# Generated by Django 3.2.5 on 2021-08-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Team_Typte',
        ),
        migrations.AddField(
            model_name='team',
            name='Team_Typte',
            field=models.ManyToManyField(blank=True, null=True, to='teams.Team_Categories'),
        ),
    ]
