# Generated by Django 3.2.5 on 2021-08-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamplayers',
            old_name='Team',
            new_name='Team_Name',
        ),
    ]
