# Generated by Django 3.2.5 on 2021-08-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Game',
        ),
    ]
