# Generated by Django 3.2.5 on 2021-08-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20210802_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Team_Typte',
            field=models.ManyToManyField(to='teams.Team_Categories'),
        ),
    ]
