# Generated by Django 3.2.5 on 2021-08-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20210802_0221'),
        ('teams', '0003_alter_team_team_typte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_Categories',
            new_name='TeamCategories',
        ),
        migrations.RenameModel(
            old_name='Team_Players',
            new_name='TeamPlayers',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Team_About',
            new_name='TeamAbout',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Team_Name',
            new_name='TeamName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Team_Typte',
        ),
        migrations.AddField(
            model_name='team',
            name='TeamTypte',
            field=models.ManyToManyField(to='teams.TeamCategories'),
        ),
    ]
