# Generated by Django 5.2.1 on 2025-05-21 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_otherlineup'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tenants.tenant'),
        ),
    ]
