# Generated by Django 3.2.25 on 2026-08-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_otherlineup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralteam',
            name='BS_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='otherlineup',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
