# Generated by Django 3.2.25 on 2026-08-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_seed_default_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentpayment',
            name='gateway',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentpayment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tournamentpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tournamentpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('paid', 'Paid'), ('failed', 'Failed'), ('waived', 'Waived')], default='pending', max_length=10),
        ),
    ]
