# Generated by Django 3.2.25 on 2026-08-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_auto_20260809_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='draw_label',
            field=models.CharField(default='Draw', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='points_draw',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='points_loss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='points_win',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='game',
            name='score_noun',
            field=models.CharField(default='goals', max_length=20),
        ),
    ]
