# Generated by Django 3.2.5 on 2021-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Countdown_Expected',
            field=models.BooleanField(default=False),
        ),
    ]
