# Generated by Django 3.2.5 on 2021-08-08 19:36

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredteams',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='playerspointtable',
            name='Match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
        migrations.AddField(
            model_name='playerspointtable',
            name='player',
            field=smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='player', null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.teamplayers'),
        ),
        migrations.AddField(
            model_name='playerspointtable',
            name='teamName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.registeredteams'),
        ),
        migrations.AddField(
            model_name='matchround',
            name='Tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.tournament'),
        ),
        migrations.AddField(
            model_name='matchgroup',
            name='Round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.matchround'),
        ),
        migrations.AddField(
            model_name='matchgroup',
            name='Tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='Match_Group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.matchgroup'),
        ),
        migrations.AddField(
            model_name='match',
            name='Match_Round',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matches.matchround'),
        ),
        migrations.AddField(
            model_name='match',
            name='Match_Tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matches.tournament'),
        ),
    ]
