# Generated by Django 3.2.25 on 2026-08-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20260809_0034'),
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='organizers.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='organizers.organizer'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Registration open'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='draft', max_length=12),
        ),
    ]
