# Generated by Django 3.2.5 on 2021-08-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='image',
            field=models.ImageField(blank=True, default='../static/Soldier.png', null=True, upload_to='matches'),
        ),
    ]
