# Generated by Django 3.2.5 on 2021-08-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_countdown_expected'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Round_title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SEASON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SEASON_title', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='match',
            old_name='MatchTitle',
            new_name='Match_Title',
        ),
        migrations.RenameField(
            model_name='matchteamdetails',
            old_name='PointTable',
            new_name='Match_Point',
        ),
        migrations.RenameField(
            model_name='playerspointtable',
            old_name='point',
            new_name='kills',
        ),
        migrations.RemoveField(
            model_name='match',
            name='MatchCategory',
        ),
        migrations.RemoveField(
            model_name='match',
            name='MatchLevel',
        ),
        migrations.AlterField(
            model_name='match',
            name='TimeDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MatchCategories',
        ),
        migrations.DeleteModel(
            name='MatchLevel',
        ),
        migrations.AddField(
            model_name='matchround',
            name='Season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.season'),
        ),
        migrations.AddField(
            model_name='match',
            name='Match_Round',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matches.matchround'),
        ),
        migrations.AddField(
            model_name='match',
            name='Match_SEASON',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matches.season'),
        ),
    ]
