# Generated by Django 3.2.5 on 2021-08-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20210802_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='matche',
            name='Score_of_Team_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matche',
            name='Match_Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='matches.matche_level'),
        ),
        migrations.AlterField(
            model_name='matche',
            name='Score_of_Team_1',
            field=models.IntegerField(default=0),
        ),
    ]
