# Generated by Django 3.2.5 on 2021-08-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='mvp_expected',
            field=models.BooleanField(default=False),
        ),
    ]
