# Generated by Django 3.2.5 on 2021-08-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20210802_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='matche',
            name='Matche_About',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='matche',
            name='Time_Date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
