# Generated by Django 3.2.5 on 2021-08-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_tournament_mvp_expected'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Use_to_rank_player',
            field=models.BooleanField(default=False),
        ),
    ]
