# Generated by Django 3.2.5 on 2021-08-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20210804_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Match_Title',
            field=models.CharField(max_length=100),
        ),
    ]
