# Generated by Django 3.2.25 on 2026-08-09 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20260809_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=80)),
                ('captain_name', models.CharField(max_length=80)),
                ('captain_phone', models.CharField(max_length=20)),
                ('captain_email', models.EmailField(blank=True, max_length=254)),
                ('roster', models.TextField(blank=True, help_text='One player per line.', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='matches.tournament')),
                ('tournament_team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='matches.tournamentteam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
