# Generated by Django 3.2.5 on 2021-08-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchgroup',
            name='Group_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='Round_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='SEASON_title',
            field=models.CharField(max_length=100),
        ),
    ]
