# Generated by Django 3.2.5 on 2021-08-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_use_to_rank_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='Use_to_rank_player',
            new_name='Use_for_Ranking',
        ),
    ]
