# Generated by Django 3.2.5 on 2021-08-02 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_team_typte'),
        ('players', '0002_auto_20210802_0221'),
        ('matches', '0004_auto_20210802_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Featured', models.BooleanField(default=False)),
                ('Time_Date', models.TimeField(blank=True, null=True)),
                ('Match_About', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match_Team_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point_Table', models.IntegerField(default=0)),
                ('Match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Players_point_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveBigIntegerField(default=0)),
                ('Match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
        migrations.RenameModel(
            old_name='Matche_Level',
            new_name='Match_Categories',
        ),
        migrations.RenameModel(
            old_name='Matche_Categories',
            new_name='Match_Level',
        ),
        migrations.DeleteModel(
            name='Matche',
        ),
        migrations.AddField(
            model_name='match',
            name='Match_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='matches.match_categories'),
        ),
        migrations.AddField(
            model_name='match',
            name='Match_Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='matches.match_level'),
        ),
    ]
