# Generated by Django 3.2.5 on 2021-08-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_team_typte'),
        ('players', '0002_auto_20210802_0221'),
        ('matches', '0005_auto_20210802_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_team_details',
            name='Match',
        ),
        migrations.RemoveField(
            model_name='players_point_table',
            name='Match',
        ),
        migrations.AddField(
            model_name='match',
            name='MatchTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match_team_details',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
        migrations.AddField(
            model_name='players_point_table',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
        migrations.AlterField(
            model_name='match_team_details',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='players_point_table',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
    ]
