# Generated by Django 3.2.5 on 2021-08-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_rename_use_to_rank_player_match_use_for_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='number_of_mvp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
