# Generated by Django 3.2.5 on 2021-08-08 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20210807_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Match_Group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.matchgroup'),
        ),
    ]
