# Generated by Django 3.2.5 on 2021-08-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20210802_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_team_details',
            old_name='match',
            new_name='Match',
        ),
        migrations.RenameField(
            model_name='players_point_table',
            old_name='match',
            new_name='Match',
        ),
    ]
