# Generated by Django 3.2.5 on 2021-08-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_team_typte'),
        ('players', '0002_auto_20210802_0221'),
        ('matches', '0007_auto_20210802_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match_Categories',
            new_name='MatchCategories',
        ),
        migrations.RenameModel(
            old_name='Match_Level',
            new_name='MatchLevel',
        ),
        migrations.RenameModel(
            old_name='Match_Team_Details',
            new_name='MatchTeamDetails',
        ),
        migrations.RenameModel(
            old_name='Players_point_table',
            new_name='PlayersPointTable',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='Match_About',
            new_name='MatchAbout',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='Time_Date',
            new_name='TimeDate',
        ),
        migrations.RenameField(
            model_name='matchteamdetails',
            old_name='Point_Table',
            new_name='PointTable',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Match_Category',
        ),
        migrations.RemoveField(
            model_name='match',
            name='Match_Level',
        ),
        migrations.AddField(
            model_name='match',
            name='MatchCategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matches.matchcategories'),
        ),
        migrations.AddField(
            model_name='match',
            name='MatchLevel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matches.matchlevel'),
        ),
    ]
