# Generated by Django 3.2.5 on 2021-08-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_matchround_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchround',
            name='about',
        ),
        migrations.AddField(
            model_name='tournament',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
