# Generated by Django 3.2.5 on 2021-08-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20210802_1458'),
        ('matches', '0008_auto_20210802_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerspointtable',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
