# Generated by Django 3.2.5 on 2021-08-03 22:09

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_speciality'),
        ('matches', '0008_alter_playerspointtable_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerspointtable',
            name='player',
            field=smart_selects.db_fields.GroupedForeignKey(blank=True, group_field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'), null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
    ]
