# Generated by Django 3.2.5 on 2021-08-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_playerspointtable_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerspointtable',
            old_name='Team',
            new_name='teamName',
        ),
    ]
