# Generated by Django 3.2.5 on 2021-08-08 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_auto_20210808_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.tournament'),
        ),
    ]
