# Generated by Django 3.2.5 on 2021-08-04 06:35

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_speciality'),
        ('matches', '0010_rename_team_playerspointtable_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerspointtable',
            name='player',
            field=smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='teamName', null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
    ]
