# Generated by Django 3.2.5 on 2021-08-04 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_auto_20210804_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerspointtable',
            name='teamName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.registeredteams'),
        ),
    ]
