# Generated by Django 3.2.5 on 2021-08-04 09:12

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_rename_team_teamplayers_team_name'),
        ('matches', '0023_auto_20210804_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerspointtable',
            name='team_Name',
        ),
        migrations.AddField(
            model_name='playerspointtable',
            name='player',
            field=smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='player', null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.teamplayers'),
        ),
        migrations.AddField(
            model_name='playerspointtable',
            name='teamName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.registeredteams'),
        ),
    ]
