# Generated by Django 3.2.5 on 2021-08-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0024_auto_20210804_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerspointtable',
            old_name='kills',
            new_name='kill_Point',
        ),
        migrations.RenameField(
            model_name='registeredteams',
            old_name='Match_Point',
            new_name='Placement_Point',
        ),
        migrations.AddField(
            model_name='registeredteams',
            name='total_Point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
