# Generated by Django 3.2.5 on 2021-08-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0025_auto_20210804_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerspointtable',
            name='Match_SEASON',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matches.season'),
        ),
        migrations.AddField(
            model_name='registeredteams',
            name='Match_SEASON',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matches.season'),
        ),
    ]
