# Generated by Django 3.2.5 on 2021-08-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0026_auto_20210804_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerspointtable',
            name='Match_SEASON',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.season'),
        ),
        migrations.AlterField(
            model_name='registeredteams',
            name='Match_SEASON',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.season'),
        ),
    ]
