# Generated by Django 3.2.5 on 2021-08-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0027_auto_20210804_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerspointtable',
            name='Match_SEASON',
        ),
        migrations.RemoveField(
            model_name='registeredteams',
            name='Match_SEASON',
        ),
        migrations.AddField(
            model_name='registeredteams',
            name='Win',
            field=models.BooleanField(default=False),
        ),
    ]
