# Generated by Django 3.2.5 on 2021-08-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0029_alter_registeredteams_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
