# Generated by Django 3.0.7 on 2021-07-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('about', models.TextField(blank=True, max_length=400, null=True)),
                ('speciality', models.TextField(blank=True, max_length=200, null=True)),
                ('present_position', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
