# Generated by Django 3.2.5 on 2021-08-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, default='../static/Soldier.png', null=True, upload_to='players')),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=400, null=True)),
                ('speciality', models.CharField(blank=True, max_length=200, null=True)),
                ('present_position', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
