# Generated by Django 3.2.5 on 2021-08-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
        migrations.AddField(
            model_name='player',
            name='in_game_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
