# Generated by Django 3.2.5 on 2021-08-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='../static/Soldier.png', null=True, upload_to='players'),
        ),
    ]
