# Generated by Django 5.2.1 on 2025-05-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mvp_awards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_kills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_matches_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
